# Generated by Django 4.1.7 on 2025-01-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=20)),
                ('minutes', models.IntegerField(default=15)),
                ('item1', models.CharField(max_length=10)),
                ('item2', models.CharField(max_length=10)),
                ('item3', models.CharField(max_length=10)),
                ('uuid', models.IntegerField(default=0)),
            ],
        ),
    ]
